### ISSUE TITLE
Population inaccurate

### ISSUE THREAD

**Issue by tony19** [JamesMilnerUK/github-map#9]
It seems the indicated populations exceed the census record by a vast margin (more than 100% in some cases). How is the population size determined in the app data?

* New York City
  - Expected population: 8.6M ([2015](https://en.wikipedia.org/wiki/New_York_City#Population_density))
  - Actual: 18.6M
![screen shot 2017-02-24 at 3 02 47 pm](https://cloud.githubusercontent.com/assets/26580/23320939/a4caa484-faa2-11e6-87d6-cee61a2416a5.png)

* San Francisco
  - Expected population: 852K ([2014](https://en.wikipedia.org/wiki/Demographics_of_San_Francisco))
  - Actual: 3.3M
 ![screen shot 2017-02-24 at 3 02 31 pm](https://cloud.githubusercontent.com/assets/26580/23320896/57b41144-faa2-11e6-976b-174c6b142e58.png)

**Comment by JamesLMilner** [comment]
It comes form the from the United Nations, Department of Economic and Social Affairs, Population Division, 2014. The problem you're seeing is probably based on how you determine the boundaries of a city. It's hard to say what to suggest, because I assume at least with the data provided, the criteria they used to determine populations and boundaries were at least consistent.

**Comment by tony19** [comment]
Ok, I see. They must be using metropolitan area, but the numbers still seem significantly excessive.
